### ISSUE TITLE
[Suggestion] AMP redirect

### ISSUE THREAD

**Issue by BirdInFire** [underrobyn/AbsoluteDoubleTrace#63]
AMP page is used by some shitty entreprise (Google, Microsoft bing), for displaying a website on their server and track the user.
Is it possible with script we can found easily on github redirect those AMP page to their native HTML page ?

Thanks

**Comment by jake-cryptic** [comment]
Hi,

I think that's a good idea which I would implement in the future however since the userbase for Trace on Firefox mobile is quite small it's not something I will be looking into just yet.

Thanks

**Comment by aelisya** [comment]
actually i was thinking about desktop one, sometime i receive amp page from a mobile user, so i have to search the page on their website because if i click on the page who have a link like this "https://www.google.com/amp/website/amp/" even if i'm on desktop, i will be tracked

**Comment by aelisya** [comment]
so convert https://cdn.ampproject.org/c/s/www.example.com/amp/document to https://www.example.com/amp/document, can help on desktop to bypass tracking

**Comment by brian6932** [comment]
In case anyone wants this functionality you can get it from:
https://addons.mozilla.org/firefox/addon/amp2html/
https://chrome.google.com/webstore/detail/redirect-amp-to-html/kifkmmpiicbcnkjaliilaoeaojlldonl

**Comment by michaelb-ae** [comment]
> Incase anyone wants this functionality you can get it from:
> https://addons.mozilla.org/en-US/firefox/addon/amp2html/
> https://chrome.google.com/webstore/detail/redirect-amp-to-html/kifkmmpiicbcnkjaliilaoeaojlldonl

yes and i have done an extension on the edge store who do that (for those who use it of course) : https://microsoftedge.microsoft.com/addons/detail/aelisya/ackodolhpbogckmcjkfdcgifhigeghkg
