### ISSUE TITLE
Additional tracking parameters for URL Tracking Cleaner

### ISSUE THREAD

**Issue by gschmidl** [underrobyn/AbsoluteDoubleTrace#66]
If at all possible, it would be nice to be able to manually add parameters to URL Tracking Cleaner's configuration - for example, Twitter has a ref_src parameter that's not in there, nor Facebook's fbclid.

If not, I'd be grateful if you could add that :-)

**Comment by code3z** [comment]
In addition, limit cleaning to certain frames?
(Only main frame by default)
